(function (global) {
  "use strict";

  const DEFAULT_NAME = "YOLO Tensor Boxes";

  function createControls(parent, getSequence) {
    const parentElement = parent && parent.elt ? parent.elt : parent;
    if (!parentElement || typeof getSequence !== "function") {
      return;
    }

    const exportTitle = document.createElement("div");
    exportTitle.className = "layer-controls__title";
    exportTitle.textContent = "Export";
    parentElement.appendChild(exportTitle);

    addExportButton(parentElement, "Save as AfterEffects JSX", () => saveAfterEffectsJsx(getSequence()));
    addExportButton(parentElement, "Save as Blender Python", () => saveBlenderPython(getSequence()));
    addExportButton(parentElement, "Save as Maya Python", () => saveMayaPython(getSequence()));
  }

  function addExportButton(parentElement, label, handler) {
    const button = document.createElement("button");
    button.className = "export-button";
    button.type = "button";
    button.textContent = label;
    button.addEventListener("click", handler);
    parentElement.appendChild(button);
  }

  function saveAfterEffectsJsx(sequence) {
    const data = buildExportData(sequence);
    if (!data) {
      return;
    }
    downloadTextFile(exportFilename(sequence, "aftereffects", "jsx"), buildAfterEffectsJsx(data));
  }

  function saveBlenderPython(sequence) {
    const data = buildExportData(sequence);
    if (!data) {
      return;
    }
    downloadTextFile(exportFilename(sequence, "blender", "py"), buildBlenderPython(data));
  }

  function saveMayaPython(sequence) {
    const data = buildExportData(sequence);
    if (!data) {
      return;
    }
    downloadTextFile(exportFilename(sequence, "maya", "py"), buildMayaPython(data));
  }

  function buildExportData(sequence) {
    if (!sequence || !Array.isArray(sequence.frames) || sequence.frames.length === 0) {
      return null;
    }

    const tracks = new Map();
    for (let frameIndex = 0; frameIndex < sequence.frames.length; frameIndex += 1) {
      const boxes = sequence.frames[frameIndex] || [];
      for (let boxIndex = 0; boxIndex < boxes.length; boxIndex += 1) {
        const box = boxes[boxIndex];
        const key = String(boxIndex);
        if (!tracks.has(key)) {
          tracks.set(key, {
            id: boxIndex,
            label: `box${boxIndex}`,
            color: [80, 255, 80],
            frames: [],
          });
        }

        tracks.get(key).frames.push({
          frame: frameIndex,
          bbox: [
            roundForExport(box.x - box.w / 2),
            roundForExport(box.y - box.h / 2),
            roundForExport(box.w),
            roundForExport(box.h),
          ],
          point: [roundForExport(box.x), roundForExport(box.y)],
          visible: true,
        });
      }
    }

    return {
      name: sequence.name || exportBaseName(sequence) || DEFAULT_NAME,
      sourceFileName: sequence.sourceFileName || "piles_detected_boxes.txt",
      sourceBaseName: exportBaseName(sequence),
      width: sequence.width || 1280,
      height: sequence.height || 720,
      fps: sequence.fps || 30,
      frameCount: sequence.frames.length,
      tracks: Array.from(tracks.values()),
    };
  }

  function buildAfterEffectsJsx(data) {
    return [
      "// Generated by p5 YOLO tensor visualizer.",
      "// Run in After Effects with File > Scripts > Run Script File...",
      "app.beginUndoGroup(\"Import YOLO tensor boxes\");",
      `var data = ${JSON.stringify(data, null, 2)};`,
      aeHelperSource(),
      "var comp = app.project.items.addComp(data.name, data.width, data.height, 1, data.frameCount / data.fps, data.fps);",
      "comp.bgColor = [0, 0, 0];",
      "for (var i = 0; i < data.tracks.length; i += 1) {",
      "  importTrack(comp, data, data.tracks[i]);",
      "}",
      "app.endUndoGroup();",
      "",
    ].join("\n");
  }

  function aeHelperSource() {
    return `
function color01(color) {
  return [color[0] / 255, color[1] / 255, color[2] / 255];
}

function cleanName(value) {
  var text = String(value);
  var forbidden = [92, 47, 58, 42, 63, 34, 60, 62, 124];
  for (var i = 0; i < forbidden.length; i += 1) {
    text = text.split(String.fromCharCode(forbidden[i])).join("_");
  }
  return text;
}

function makeShape(points, closed) {
  var shape = new Shape();
  var inTangents = [];
  var outTangents = [];
  for (var i = 0; i < points.length; i += 1) {
    inTangents.push([0, 0]);
    outTangents.push([0, 0]);
  }
  shape.vertices = points;
  shape.inTangents = inTangents;
  shape.outTangents = outTangents;
  shape.closed = closed;
  return shape;
}

function frameAt(track, frameIndex) {
  for (var i = 0; i < track.frames.length; i += 1) {
    if (track.frames[i].frame === frameIndex) {
      return track.frames[i];
    }
  }
  return null;
}

function addBoxLayer(comp, track) {
  var layer = comp.layers.addShape();
  layer.name = cleanName(track.label + " #" + track.id + " bbox");
  var transform = layer.property("ADBE Transform Group");
  transform.property("ADBE Anchor Point").setValue([0, 0]);
  transform.property("ADBE Position").setValue([0, 0]);
  var contents = layer.property("ADBE Root Vectors Group");
  var group = contents.addProperty("ADBE Vector Group");
  var vectors = group.property("ADBE Vectors Group");
  var pathGroup = vectors.addProperty("ADBE Vector Shape - Group");
  pathGroup.name = "Box Path";
  var stroke = vectors.addProperty("ADBE Vector Graphic - Stroke");
  stroke.property("ADBE Vector Stroke Color").setValue(color01(track.color));
  stroke.property("ADBE Vector Stroke Width").setValue(2);
  return {
    path: vectors.property("Box Path").property("ADBE Vector Shape"),
    opacity: transform.property("ADBE Opacity")
  };
}

function importTrack(comp, data, track) {
  var boxLayer = addBoxLayer(comp, track);
  for (var frameIndex = 0; frameIndex < data.frameCount; frameIndex += 1) {
    var frame = frameAt(track, frameIndex);
    var time = frameIndex / data.fps;
    boxLayer.opacity.setValueAtTime(time, frame ? 100 : 0);
    if (frame && frame.bbox) {
      var b = frame.bbox;
      boxLayer.path.setValueAtTime(time, makeShape([[b[0], b[1]], [b[0] + b[2], b[1]], [b[0] + b[2], b[1] + b[3]], [b[0], b[1] + b[3]]], true));
    }
  }
}
`;
  }

  function buildBlenderPython(data) {
    return [
      "# Generated by p5 YOLO tensor visualizer.",
      "# In Blender: Scripting workspace > open this file > Run Script.",
      "import json",
      "import bpy",
      "",
      `DATA = json.loads(${JSON.stringify(JSON.stringify(data))})`,
      blenderHelperSource(),
      "import_yolo_boxes(DATA)",
      "",
    ].join("\n");
  }

  function blenderHelperSource() {
    return `
SCALE = 0.01

def safe_name(value):
    text = str(value)
    for ch in '\\\\/:*?"<>| #':
        text = text.replace(ch, '_')
    return text

def map_point(point, data):
    return (
        (float(point[0]) - float(data['width']) * 0.5) * SCALE,
        0.0,
        (float(data['height']) * 0.5 - float(point[1])) * SCALE,
    )

def material_for(track):
    name = 'YOLO_Box_Material_' + safe_name(track['id'])
    material = bpy.data.materials.get(name) or bpy.data.materials.new(name)
    color = track.get('color', [80, 255, 80])
    material.diffuse_color = (float(color[0]) / 255.0, float(color[1]) / 255.0, float(color[2]) / 255.0, 1.0)
    return material

def make_curve_object(name, points, material, collection):
    curve = bpy.data.curves.new(name, 'CURVE')
    curve.dimensions = '3D'
    curve.resolution_u = 1
    curve.bevel_depth = 0.004
    curve.bevel_resolution = 0
    spline = curve.splines.new('POLY')
    spline.points.add(len(points) - 1)
    for point, co in zip(spline.points, points):
        point.co = (co[0], co[1], co[2], 1.0)
    obj = bpy.data.objects.new(name, curve)
    obj.data.materials.append(material)
    collection.objects.link(obj)
    return obj

def key_visibility(obj, frame, visible):
    obj.hide_viewport = not visible
    obj.hide_render = not visible
    obj.keyframe_insert(data_path='hide_viewport', frame=frame)
    obj.keyframe_insert(data_path='hide_render', frame=frame)

def key_single_frame_visibility(obj, frame, frame_count):
    if frame > 1:
        key_visibility(obj, frame - 1, False)
    key_visibility(obj, frame, True)
    if frame < frame_count:
        key_visibility(obj, frame + 1, False)

def make_bbox_points(bbox, data):
    x, y, w, h = bbox
    return [
        map_point([x, y], data),
        map_point([x + w, y], data),
        map_point([x + w, y + h], data),
        map_point([x, y + h], data),
        map_point([x, y], data),
    ]

def import_yolo_boxes(data):
    scene = bpy.context.scene
    scene.frame_start = 1
    scene.frame_end = int(data['frameCount'])
    scene.render.fps = int(round(float(data['fps'])))
    root_name = safe_name(data.get('name') or data.get('sourceBaseName') or 'YOLO_Tensor_Boxes')
    root = bpy.data.collections.new(root_name)
    scene.collection.children.link(root)

    for track in data.get('tracks', []):
        material = material_for(track)
        track_collection = bpy.data.collections.new('Track_' + safe_name(track['label'] + '_' + str(track['id'])))
        root.children.link(track_collection)
        for frame in track.get('frames', []):
            blender_frame = int(frame['frame']) + 1
            obj = make_curve_object('BBox_' + safe_name(track['label']) + '_f' + str(frame['frame']), make_bbox_points(frame['bbox'], data), material, track_collection)
            key_single_frame_visibility(obj, blender_frame, int(data['frameCount']))

    scene.frame_set(1)
    print('YOLO tensor box import complete: %d tracks, %d frames' % (len(data.get('tracks', [])), int(data['frameCount'])))
`;
  }

  function buildMayaPython(data) {
    return [
      "# Generated by p5 YOLO tensor visualizer.",
      "# In Maya: Script Editor > Python tab > open or paste this file > Run.",
      "import json",
      "import maya.cmds as cmds",
      "",
      `DATA = json.loads(${JSON.stringify(JSON.stringify(data))})`,
      mayaHelperSource(),
      "import_yolo_boxes(DATA)",
      "",
    ].join("\n");
  }

  function mayaHelperSource() {
    return `
SCALE = 0.01

def safe_name(value):
    text = str(value)
    for ch in '\\\\/:*?"<>| #':
        text = text.replace(ch, '_')
    return text

def map_point(point, data):
    return (
        (float(point[0]) - float(data['width']) * 0.5) * SCALE,
        0.0,
        (float(data['height']) * 0.5 - float(point[1])) * SCALE,
    )

def apply_curve_color(curve, track):
    color = track.get('color', [80, 255, 80])
    cmds.setAttr(curve + '.overrideEnabled', 1)
    cmds.setAttr(curve + '.overrideRGBColors', 1)
    cmds.setAttr(curve + '.overrideColorRGB', float(color[0]) / 255.0, float(color[1]) / 255.0, float(color[2]) / 255.0)

def key_visibility(node, frame, visible):
    cmds.setAttr(node + '.visibility', bool(visible))
    cmds.setKeyframe(node, attribute='visibility', time=frame)

def key_single_frame_visibility(node, frame, frame_count):
    if frame > 1:
        key_visibility(node, frame - 1, False)
    key_visibility(node, frame, True)
    if frame < frame_count:
        key_visibility(node, frame + 1, False)

def set_time_unit(fps):
    fps = float(fps)
    if abs(fps - 24.0) < 0.01:
        cmds.currentUnit(time='film')
    elif abs(fps - 25.0) < 0.01:
        cmds.currentUnit(time='pal')
    elif abs(fps - 30.0) < 0.01:
        cmds.currentUnit(time='ntsc')
    elif abs(fps - 48.0) < 0.01:
        cmds.currentUnit(time='show')
    elif abs(fps - 60.0) < 0.01:
        cmds.currentUnit(time='ntscf')

def make_bbox_points(bbox, data):
    x, y, w, h = bbox
    return [
        map_point([x, y], data),
        map_point([x + w, y], data),
        map_point([x + w, y + h], data),
        map_point([x, y + h], data),
        map_point([x, y], data),
    ]

def import_yolo_boxes(data):
    set_time_unit(data.get('fps', 30))
    cmds.playbackOptions(minTime=1, maxTime=int(data['frameCount']), animationStartTime=1, animationEndTime=int(data['frameCount']))
    root_name = safe_name(data.get('name') or data.get('sourceBaseName') or 'YOLO_Tensor_Boxes')
    root = cmds.group(empty=True, name=root_name)

    for track in data.get('tracks', []):
        group = cmds.group(empty=True, name='Track_' + safe_name(track['label'] + '_' + str(track['id'])), parent=root)
        for frame in track.get('frames', []):
            maya_frame = int(frame['frame']) + 1
            curve = cmds.curve(degree=1, point=make_bbox_points(frame['bbox'], data), name='BBox_' + safe_name(track['label']) + '_f' + str(frame['frame']))
            apply_curve_color(curve, track)
            cmds.parent(curve, group)
            key_single_frame_visibility(curve, maya_frame, int(data['frameCount']))

    cmds.currentTime(1)
    print('YOLO tensor box import complete: %d tracks, %d frames' % (len(data.get('tracks', [])), int(data['frameCount'])))
`;
  }

  function downloadTextFile(filename, text) {
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  }

  function exportFilename(sequence, target, extension) {
    return `${exportBaseName(sequence)}_${target}_${timestampForFilename(new Date())}.${extension}`;
  }

  function timestampForFilename(date) {
    return [
      date.getFullYear(),
      pad2(date.getMonth() + 1),
      pad2(date.getDate()),
      pad2(date.getHours()),
      pad2(date.getMinutes()),
    ].join("");
  }

  function exportBaseName(sequence) {
    const source = sequence && (sequence.sourceBaseName || sequence.sourceFileName);
    return sanitizeFilenameBase(removeExtension(source || "piles_detected_boxes")) || "piles_detected_boxes";
  }

  function removeExtension(filename) {
    return String(filename).replace(/\.[^/.\\]+$/, "");
  }

  function sanitizeFilenameBase(value) {
    return String(value)
      .trim()
      .replace(/[^A-Za-z0-9._-]+/g, "_")
      .replace(/^_+|_+$/g, "");
  }

  function pad2(value) {
    return String(value).padStart(2, "0");
  }

  function roundForExport(value) {
    return Math.round(value * 1000) / 1000;
  }

  global.YoloBoxExporter = {
    createControls,
    buildExportData,
    buildAfterEffectsJsx,
    buildBlenderPython,
    buildMayaPython,
  };
})(window);
