/**
 * Shared DOM handles and mutable runtime state.
 *
 * This module centralizes the app's queried DOM elements, paper preset catalog, and the grouped
 * state objects used across the rest of the codebase.
 */
/**
 * Preset paper dimensions used only for aspect ratio and UI convenience.
 */
export const PAPER_PRESETS = {
  letter: { width: 11, height: 8.5 },
  legal: { width: 14, height: 8.5 },
  tabloid: { width: 17, height: 11 },
  "12x9": { width: 12, height: 9 },
  "18x12": { width: 18, height: 12 },
  "24x18": { width: 24, height: 18 },
  "36x24": { width: 36, height: 24 },
  a4: { width: 297, height: 210 },
  a3: { width: 420, height: 297 },
  a2: { width: 594, height: 420 },
  a1: { width: 841, height: 594 },
};

/**
 * Cached DOM handles used throughout the app.
 */
const q = (selector) => document.querySelector(selector);

const domGroups = {
  shell: {
    appShell: q("#appShell"),
    controlPanel: q("#controlPanel"),
    workspace: q("#workspace"),
  },
  mobile: {
    mobileControlStack: q("#mobileControlStack"),
    mobileControlTabs: q("#mobileControlTabs"),
    mobileControlTabLayout: q("#mobileControlTabLayout"),
    mobileControlTabPageGrid: q("#mobileControlTabPageGrid"),
    mobileControlTabAlignment: q("#mobileControlTabAlignment"),
    mobileControlTabAppearance: q("#mobileControlTabAppearance"),
    mobileControlTabCrop: q("#mobileControlTabCrop"),
    mobileControlTabExport: q("#mobileControlTabExport"),
  },
  source: {
    dropZone: q("#dropZone"),
    fileInput: q("#fileInput"),
    loadDemoSelect: q("#loadDemoSelect"),
  },
  groups: {
    layoutGroup: q("#layoutGroup"),
    pageGridDetectionGroup: q("#pageGridDetectionGroup"),
    frameAlignmentGroup: q("#frameAlignmentGroup"),
    appearanceGroup: q("#appearanceGroup"),
    cropGeometryGroup: q("#cropGeometryGroup"),
    exportOptionsGroup: q("#exportOptionsGroup"),
    statusGroup: q("#statusGroup"),
  },
  layout: {
    paperOrientationField: q("#paperOrientationField"),
    paperOrientationLandscape: q("#paperOrientationLandscape"),
    paperOrientationPortrait: q("#paperOrientationPortrait"),
    paperPresetLabel: q("#paperPresetLabel"),
    paperPreset: q("#paperPreset"),
    customPaperFields: q("#customPaperFields"),
    paperWidth: q("#paperWidth"),
    paperHeight: q("#paperHeight"),
    frameCols: q("#frameCols"),
    frameRows: q("#frameRows"),
  },
  pageDetection: {
    pageGridDetectionSummary: q("#pageGridDetectionSummary"),
    pageGridDetectionWarning: q("#pageGridDetectionWarning"),
    lightOnDarkDesignRow: q("#lightOnDarkDesignRow"),
    lightOnDarkDesign: q("#lightOnDarkDesign"),
    thresholdMethod: q("#thresholdMethod"),
    thresholdOffset: q("#thresholdOffset"),
    thresholdOffsetValue: q("#thresholdOffsetValue"),
    paperMarginRow: q("#paperMarginRow"),
    paperMargin: q("#paperMargin"),
    paperMarginValue: q("#paperMarginValue"),
    boundarySensitivityRow: q("#boundarySensitivityRow"),
    boundarySensitivity: q("#boundarySensitivity"),
    boundarySensitivityValue: q("#boundarySensitivityValue"),
    boundaryPersistenceRow: q("#boundaryPersistenceRow"),
    boundaryPersistence: q("#boundaryPersistence"),
    boundaryPersistenceValue: q("#boundaryPersistenceValue"),
  },
  alignment: {
    alignmentPipelineField: q("#alignmentPipelineField"),
    alignmentPipelineMarkerless: q("#alignmentPipelineMarkerless"),
    alignmentPipelineMarkers: q("#alignmentPipelineMarkers"),
    alignmentSliderStack: q("#alignmentSliderStack"),
    crossRoiScaleRow: q("#crossRoiScaleRow"),
    crossRoiScaleLabel: q("#crossRoiScaleLabel"),
    crossRoiScale: q("#crossRoiScale"),
    crossRoiScaleValue: q("#crossRoiScaleValue"),
    stabilizationStrengthRow: q("#stabilizationStrengthRow"),
    stabilizationStrength: q("#stabilizationStrength"),
    stabilizationStrengthValue: q("#stabilizationStrengthValue"),
    stabilizationLambdaRow: q("#stabilizationLambdaRow"),
    stabilizationLambda: q("#stabilizationLambda"),
    stabilizationLambdaValue: q("#stabilizationLambdaValue"),
    markerlessPhaseDebugRow: q("#markerlessPhaseDebugRow"),
    markerlessPhaseDebug: q("#markerlessPhaseDebug"),
    markerlessUseDarknessRow: q("#markerlessUseDarknessRow"),
    markerlessUseDarkness: q("#markerlessUseDarkness"),
    markerlessUseTextureRow: q("#markerlessUseTextureRow"),
    markerlessUseTexture: q("#markerlessUseTexture"),
    markerlessUseVarianceRow: q("#markerlessUseVarianceRow"),
    markerlessUseVariance: q("#markerlessUseVariance"),
    emphasizePeripheryRow: q("#emphasizePeripheryRow"),
    emphasizePeriphery: q("#emphasizePeriphery"),
    markerlessPhaseXRow: q("#markerlessPhaseXRow"),
    markerlessPhaseX: q("#markerlessPhaseX"),
    markerlessPhaseXValue: q("#markerlessPhaseXValue"),
    markerlessPhaseYRow: q("#markerlessPhaseYRow"),
    markerlessPhaseY: q("#markerlessPhaseY"),
    markerlessPhaseYValue: q("#markerlessPhaseYValue"),
    verticalDriftCompensationRow: q("#verticalDriftCompensationRow"),
    verticalDriftCompensation: q("#verticalDriftCompensation"),
    verticalDriftCompensationValue: q("#verticalDriftCompensationValue"),
    alignmentMarkerTypeField: q("#alignmentMarkerTypeField"),
    alignmentMarkerType: q("#alignmentMarkerType"),
    detectCrossesWithConvolutionRow: q("#detectCrossesWithConvolutionRow"),
    detectCrossesWithConvolution: q("#detectCrossesWithConvolution"),
    useCrossAlignmentRow: q("#useCrossAlignmentRow"),
    useCrossAlignment: q("#useCrossAlignment"),
  },
  cropGeometry: {
    cropLeft: q("#cropLeft"),
    cropRight: q("#cropRight"),
    cropTop: q("#cropTop"),
    cropBottom: q("#cropBottom"),
    cropAspectRatioValue: q("#cropAspectRatioValue"),
    flipHorizontal: q("#flipHorizontal"),
    flipVertical: q("#flipVertical"),
    rotate90Cw: q("#rotate90Cw"),
  },
  appearance: {
    brightness: q("#brightness"),
    brightnessValue: q("#brightnessValue"),
    contrast: q("#contrast"),
    contrastValue: q("#contrastValue"),
    vibrance: q("#vibrance"),
    vibranceValue: q("#vibranceValue"),
    temperature: q("#temperature"),
    temperatureValue: q("#temperatureValue"),
    unsharpRadius: q("#unsharpRadius"),
    unsharpRadiusValue: q("#unsharpRadiusValue"),
    unsharpAmount: q("#unsharpAmount"),
    unsharpAmountValue: q("#unsharpAmountValue"),
    invert: q("#invert"),
  },
  exportOptions: {
    fps: q("#fps"),
    loopCount: q("#loopCount"),
    outputWidth: q("#outputWidth"),
    outputHeight: q("#outputHeight"),
    gifQuality: q("#gifQuality"),
    gifQualityValue: q("#gifQualityValue"),
    gifDither: q("#gifDither"),
    gifResampling: q("#gifResampling"),
    gifGlobalPalette: q("#gifGlobalPalette"),
    reverseOrder: q("#reverseOrder"),
    boustrophedonOrder: q("#boustrophedonOrder"),
    pingPong: q("#pingPong"),
  },
  status: {
    statusText: q("#statusText"),
    statusBusy: q("#statusBusy"),
  },
  viewer: {
    viewerTabRaw: q("#viewerTabRaw"),
    viewerTabRectified: q("#viewerTabRectified"),
    viewerTabMarkers: q("#viewerTabMarkers"),
    viewerTabPreview: q("#viewerTabPreview"),
    rawViewerCard: q("#rawViewerCard"),
    rectifiedViewerCard: q("#rectifiedViewerCard"),
    markersViewerCard: q("#markersViewerCard"),
    previewViewerCard: q("#previewViewerCard"),
    rawPhotoHeading: q("#rawPhotoHeading"),
    rawCanvas: q("#rawCanvas"),
    rawPhotoHeadingText: q("#rawPhotoHeadingText"),
    rawPhotoNameWrap: q("#rawPhotoNameWrap"),
    rawPhotoName: q("#rawPhotoName"),
    rawPhotoWarning: q("#rawPhotoWarning"),
    rawBusy: q("#rawBusy"),
    rectifiedSheetHeading: q("#rectifiedSheetHeading"),
    crossRegionsHeading: q("#crossRegionsHeading"),
    rectifiedCanvas: q("#rectifiedCanvas"),
    animationPreviewHeading: q("#animationPreviewHeading"),
    gifPreviewCanvas: q("#gifPreviewCanvas"),
    gifImage: q("#gifImage"),
    crossRoiViewport: q("#crossRoiViewport"),
    crossRoiGrid: q("#crossRoiGrid"),
  },
  actions: {
    previewPlayPauseButton: q("#previewPlayPauseButton"),
    exportZipButton: q("#exportZipButton"),
    exportMp4Button: q("#exportMp4Button"),
    exportButton: q("#exportButton"),
    saveSettingsButton: q("#saveSettingsButton"),
    markerHeaderActions: q("#markerHeaderActions"),
    toggleMarkerBlobViewButton: q("#toggleMarkerBlobViewButton"),
    toggleMarkerEditingButton: q("#toggleMarkerEditingButton"),
    clearMarkerEditsButton: q("#clearMarkerEditsButton"),
    tooltipToggleButton: q("#tooltipToggleButton"),
    resetAppearanceButton: q("#resetAppearanceButton"),
    resetTrimButton: q("#resetTrimButton"),
    resetExportButton: q("#resetExportButton"),
  },
};

export const dom = Object.assign(
  {},
  ...Object.values(domGroups).map((group) => ({ ...group })),
  domGroups
);

/**
 * Shared application state, grouped by concern so cache invalidation stays explicit.
 */
export const state = {
  runtime: {
    cvReady: false,
    tooltipsEnabled: false,
    busy: false,
    pageBoundaryWarningVisible: false,
    markerEditingEnabled: false,
    markerBlobDebugVisible: false,
    markerlessPhaseDebugVisible: false,
    lastMarkerClickKey: "",
    lastMarkerClickTime: 0,
    outputWidthPx: 0,
    outputHeightPx: 0,
    outputSizeAuto: true,
    outputSizeAnchor: "auto",
    pendingOutputScale: null,
    mp4ExportSupported: false,
    mp4Codec: "avc1.42001f",
    mobileSingleViewerMode: false,
    activeViewerTab: "raw",
    activeMobileControlTab: "layout",
  },
  source: {
    image: null,
    filename: "",
    mimeType: "",
    dragUrl: "",
    ownedObjectUrl: "",
    canvas: document.createElement("canvas"),
    rawPageContour: null,
    cvMat: null,
    grayMat: null,
    previewGrayMat: null,
    previewScale: 1,
  },
  geometry: {
    alignmentInfo: null,
    baseRectifiedCanvas: null,
    baseRectifiedMat: null,
    baseRectifiedGrayMat: null,
    baseRectifiedPageCanvas: null,
    pagePreviewGridQuad: null,
    frameCount: 0,
    manualMarkerOverrides: new Map(),
  },
  frames: {
    base: [],
    stabilizedCache: new Map(),
    stabilizationPairwise: null,
    stabilizationOffsets: null,
    adjustedCache: new Map(),
  },
  preview: {
    adjustedRectifiedCanvas: document.createElement("canvas"),
    rectifiedDiagnosticCanvas: document.createElement("canvas"),
    rectifiedDiagnosticSourceCanvas: null,
    rectifiedDiagnosticDirty: true,
    rectifiedCanvas: null,
    rectifiedDragUrl: "",
    rectifiedDragBuildId: 0,
    showRectifiedDiagnostic: false,
    frameIndex: 0,
    inspectingRawFrame: false,
    lastTime: 0,
    paused: false,
    loopHandle: 0,
    resizeTimer: 0,
    exportButtonRingTimer: 0,
    appearancePreviewRaf: 0,
    appearancePreviewNeedsRectified: false,
    stabilizationPreviewRaf: 0,
    stabilizationStrengthScrubbing: false,
    stabilizationStrengthResumePlayback: false,
    markerOverrideScrubbing: false,
    markerOverrideResumePlayback: false,
    markerlessPhasePreviewRaf: 0,
    markerlessPhaseScrubbing: false,
    markerlessPhaseResumePlayback: false,
  },
  processing: {
    timer: 0,
    active: false,
    requestId: 0,
    pending: false,
  },
  export: {
    filename: "",
    url: "",
  },
};
