/**
 * Shared DOM handles and mutable runtime state.
 *
 * This module centralizes the app's queried DOM elements, paper preset catalog, and the grouped
 * state objects used across the rest of the codebase.
 */
/**
 * Preset paper dimensions used only for aspect ratio and UI convenience.
 */
export const PAPER_PRESETS = {
  letter: { width: 11, height: 8.5 },
  legal: { width: 14, height: 8.5 },
  tabloid: { width: 17, height: 11 },
  "12x9": { width: 12, height: 9 },
  "18x12": { width: 18, height: 12 },
  "24x18": { width: 24, height: 18 },
  "36x24": { width: 36, height: 24 },
  a4: { width: 297, height: 210 },
  a3: { width: 420, height: 297 },
  a2: { width: 594, height: 420 },
  a1: { width: 841, height: 594 },
};

/**
 * Cached DOM handles used throughout the app.
 */
export const dom = {
  appShell: document.querySelector("#appShell"),
  controlPanel: document.querySelector("#controlPanel"),
  workspace: document.querySelector("#workspace"),
  mobileControlStack: document.querySelector("#mobileControlStack"),
  dropZone: document.querySelector("#dropZone"),
  fileInput: document.querySelector("#fileInput"),
  loadDemoSelect: document.querySelector("#loadDemoSelect"),
  layoutGroup: document.querySelector("#layoutGroup"),
  pageGridDetectionGroup: document.querySelector("#pageGridDetectionGroup"),
  frameAlignmentGroup: document.querySelector("#frameAlignmentGroup"),
  appearanceGroup: document.querySelector("#appearanceGroup"),
  cropGeometryGroup: document.querySelector("#cropGeometryGroup"),
  exportOptionsGroup: document.querySelector("#exportOptionsGroup"),
  viewerTabRaw: document.querySelector("#viewerTabRaw"),
  viewerTabRectified: document.querySelector("#viewerTabRectified"),
  viewerTabMarkers: document.querySelector("#viewerTabMarkers"),
  viewerTabPreview: document.querySelector("#viewerTabPreview"),
  rawViewerCard: document.querySelector("#rawViewerCard"),
  rectifiedViewerCard: document.querySelector("#rectifiedViewerCard"),
  markersViewerCard: document.querySelector("#markersViewerCard"),
  previewViewerCard: document.querySelector("#previewViewerCard"),
  previewPlayPauseButton: document.querySelector("#previewPlayPauseButton"),
  exportZipButton: document.querySelector("#exportZipButton"),
  exportMp4Button: document.querySelector("#exportMp4Button"),
  exportButton: document.querySelector("#exportButton"),
  saveSettingsButton: document.querySelector("#saveSettingsButton"),
  statusGroup: document.querySelector("#statusGroup"),
  paperOrientationField: document.querySelector("#paperOrientationField"),
  paperOrientationLandscape: document.querySelector("#paperOrientationLandscape"),
  paperOrientationPortrait: document.querySelector("#paperOrientationPortrait"),
  paperPresetLabel: document.querySelector("#paperPresetLabel"),
  paperPreset: document.querySelector("#paperPreset"),
  customPaperFields: document.querySelector("#customPaperFields"),
  paperWidth: document.querySelector("#paperWidth"),
  paperHeight: document.querySelector("#paperHeight"),
  frameCols: document.querySelector("#frameCols"),
  frameRows: document.querySelector("#frameRows"),
  pageGridDetectionSummary: document.querySelector("#pageGridDetectionSummary"),
  thresholdMethod: document.querySelector("#thresholdMethod"),
  thresholdOffset: document.querySelector("#thresholdOffset"),
  thresholdOffsetValue: document.querySelector("#thresholdOffsetValue"),
  paperMargin: document.querySelector("#paperMargin"),
  paperMarginValue: document.querySelector("#paperMarginValue"),
  boundarySensitivity: document.querySelector("#boundarySensitivity"),
  boundarySensitivityValue: document.querySelector("#boundarySensitivityValue"),
  boundaryPersistence: document.querySelector("#boundaryPersistence"),
  boundaryPersistenceValue: document.querySelector("#boundaryPersistenceValue"),
  crossRoiScale: document.querySelector("#crossRoiScale"),
  crossRoiScaleValue: document.querySelector("#crossRoiScaleValue"),
  alignmentMarkerTypeField: document.querySelector("#alignmentMarkerTypeField"),
  alignmentMarkerTypeCrosses: document.querySelector("#alignmentMarkerTypeCrosses"),
  alignmentMarkerTypeCircles: document.querySelector("#alignmentMarkerTypeCircles"),
  detectCrossesWithConvolutionRow: document.querySelector("#detectCrossesWithConvolutionRow"),
  detectCrossesWithConvolution: document.querySelector("#detectCrossesWithConvolution"),
  useCrossAlignment: document.querySelector("#useCrossAlignment"),
  cropLeft: document.querySelector("#cropLeft"),
  cropRight: document.querySelector("#cropRight"),
  cropTop: document.querySelector("#cropTop"),
  cropBottom: document.querySelector("#cropBottom"),
  cropAspectRatioValue: document.querySelector("#cropAspectRatioValue"),
  flipHorizontal: document.querySelector("#flipHorizontal"),
  flipVertical: document.querySelector("#flipVertical"),
  rotate90Cw: document.querySelector("#rotate90Cw"),
  brightness: document.querySelector("#brightness"),
  brightnessValue: document.querySelector("#brightnessValue"),
  contrast: document.querySelector("#contrast"),
  contrastValue: document.querySelector("#contrastValue"),
  vibrance: document.querySelector("#vibrance"),
  vibranceValue: document.querySelector("#vibranceValue"),
  temperature: document.querySelector("#temperature"),
  temperatureValue: document.querySelector("#temperatureValue"),
  unsharpRadius: document.querySelector("#unsharpRadius"),
  unsharpRadiusValue: document.querySelector("#unsharpRadiusValue"),
  unsharpAmount: document.querySelector("#unsharpAmount"),
  unsharpAmountValue: document.querySelector("#unsharpAmountValue"),
  invert: document.querySelector("#invert"),
  fps: document.querySelector("#fps"),
  loopCount: document.querySelector("#loopCount"),
  outputWidth: document.querySelector("#outputWidth"),
  outputHeight: document.querySelector("#outputHeight"),
  gifQuality: document.querySelector("#gifQuality"),
  gifQualityValue: document.querySelector("#gifQualityValue"),
  gifDither: document.querySelector("#gifDither"),
  gifResampling: document.querySelector("#gifResampling"),
  gifGlobalPalette: document.querySelector("#gifGlobalPalette"),
  reverseOrder: document.querySelector("#reverseOrder"),
  pingPong: document.querySelector("#pingPong"),
  statusText: document.querySelector("#statusText"),
  statusBusy: document.querySelector("#statusBusy"),
  rawCanvas: document.querySelector("#rawCanvas"),
  rawPhotoNameWrap: document.querySelector("#rawPhotoNameWrap"),
  rawPhotoName: document.querySelector("#rawPhotoName"),
  rawBusy: document.querySelector("#rawBusy"),
  rectifiedSheetHeading: document.querySelector("#rectifiedSheetHeading"),
  rectifiedCanvas: document.querySelector("#rectifiedCanvas"),
  animationPreviewHeading: document.querySelector("#animationPreviewHeading"),
  gifPreviewCanvas: document.querySelector("#gifPreviewCanvas"),
  gifImage: document.querySelector("#gifImage"),
  crossRoiViewport: document.querySelector("#crossRoiViewport"),
  crossRoiGrid: document.querySelector("#crossRoiGrid"),
  markerHeaderActions: document.querySelector("#markerHeaderActions"),
  toggleMarkerEditingButton: document.querySelector("#toggleMarkerEditingButton"),
  clearMarkerEditsButton: document.querySelector("#clearMarkerEditsButton"),
  tooltipToggleButton: document.querySelector("#tooltipToggleButton"),
  resetAppearanceButton: document.querySelector("#resetAppearanceButton"),
  resetTrimButton: document.querySelector("#resetTrimButton"),
  resetExportButton: document.querySelector("#resetExportButton"),
};

/**
 * Shared application state, grouped by concern so cache invalidation stays explicit.
 */
export const state = {
  runtime: {
    cvReady: false,
    tooltipsEnabled: false,
    busy: false,
    markerEditingEnabled: false,
    lastMarkerClickKey: "",
    lastMarkerClickTime: 0,
    outputWidthPx: 0,
    outputHeightPx: 0,
    outputSizeAuto: true,
    outputSizeAnchor: "auto",
    pendingOutputScale: null,
    mp4ExportSupported: false,
    mp4Codec: "avc1.42001f",
    mobileSingleViewerMode: false,
    activeViewerTab: "raw",
  },
  source: {
    image: null,
    filename: "",
    mimeType: "",
    dragUrl: "",
    ownedObjectUrl: "",
    canvas: document.createElement("canvas"),
    rawPageContour: null,
  },
  geometry: {
    alignmentInfo: null,
    baseRectifiedCanvas: null,
    baseRectifiedPageCanvas: null,
    pagePreviewGridQuad: null,
    frameCount: 0,
    manualMarkerOverrides: new Map(),
  },
  frames: {
    base: [],
    adjustedCache: new Map(),
  },
  preview: {
    adjustedRectifiedCanvas: document.createElement("canvas"),
    rectifiedDiagnosticCanvas: document.createElement("canvas"),
    rectifiedDiagnosticSourceCanvas: null,
    rectifiedDiagnosticDirty: true,
    rectifiedCanvas: null,
    rectifiedDragUrl: "",
    rectifiedDragBuildId: 0,
    showRectifiedDiagnostic: false,
    frameIndex: 0,
    lastTime: 0,
    paused: false,
    loopHandle: 0,
    resizeTimer: 0,
    exportButtonRingTimer: 0,
    appearancePreviewRaf: 0,
    appearancePreviewNeedsRectified: false,
  },
  processing: {
    timer: 0,
    active: false,
    requestId: 0,
    pending: false,
  },
  export: {
    filename: "",
    url: "",
  },
};
